### ISSUE TITLE
panic: runtime error: slice bounds out of range [:108] with length 64

### ISSUE THREAD

**Issue by fanrong1992** [gojue/ecapture#397]
Device: Pixel6 android 13 kernel 5.10
[eCapture v0.6.2](https://github.com/gojue/ecapture/releases/tag/v0.6.2)

./ecapture tls -i wlan0 -w ecap.pcapng
tls_2023/09/25 03:02:47 ECAPTURE :: ecapture Version : androidgki_aarch64:0.6.2-20230924-5bfc790:[CORE]
tls_2023/09/25 03:02:47 ECAPTURE :: Pid Info : 24748
tls_2023/09/25 03:02:47 ECAPTURE :: Kernel Info : 5.10.157
tls_2023/09/25 03:02:47 EBPFProbeOPENSSL	module initialization
tls_2023/09/25 03:02:47 ECAPTURE ::	Module.Run()
tls_2023/09/25 03:02:47 EBPFProbeOPENSSL	TC MODEL
tls_2023/09/25 03:02:47 EBPFProbeOPENSSL	OpenSSL/BoringSSL version not found, used default version :android_default
tls_2023/09/25 03:02:47 EBPFProbeOPENSSL	HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2023/09/25 03:02:47 EBPFProbeOPENSSL	Ifname:wlan0, Ifindex:47,  Port:443, Pcapng filepath:/data/local/tmp/ecap.pcapng
tls_2023/09/25 03:02:47 EBPFProbeOPENSSL	Hook masterKey function:SSL_in_init
tls_2023/09/25 03:02:47 EBPFProbeOPENSSL	target all process. 
tls_2023/09/25 03:02:47 EBPFProbeOPENSSL	target all users. 
tls_2023/09/25 03:02:47 EBPFProbeOPENSSL	BPF bytecode filename:user/bytecode/boringssl_1_1_1_kern.o
tls_2023/09/25 03:02:49 EBPFProbeOPENSSL	readEvents error:creating PerfEventArray(skb_events)#15 reader dns: failed to create perf ring for CPU 4: can't mmap: cannot allocate memory
tls_2023/09/25 03:02:49 EBPFProbeOPENSSL	module started successfully.
tls_2023/09/25 03:02:49 ECAPTURE :: 	start 1 modules
tls_2023/09/25 03:03:04 master secret length is too long, truncate to 48 bytes, but it may cause keylog file error
tls_2023/09/25 03:03:04 TLS1_2_VERSION: save CLIENT_RANDOM adfeeb59d67e01cb4fe764ec044822b1aa4c1790ef830ec4494467e56f43b9e4 to file success, 176 bytes
tls_2023/09/25 03:03:04 master secret length is too long, truncate to 48 bytes, but it may cause keylog file error
tls_2023/09/25 03:03:04 TLS1_2_VERSION: save CLIENT_RANDOM 50722361f89b73fa7e3c2c1bcd6ac485224dbf2ff4be527c1752e1143fc28da2 to file success, 176 bytes
panic: runtime error: slice bounds out of range [:108] with length 64

goroutine 65 [running]:
ecapture/user/module.(*MOpenSSLProbe).saveMasterSecretBSSL(0x4000126dc0, 0x4003e5a400)
	/source_code/user/module/probe_openssl.go:617 +0x76c
ecapture/user/module.(*MOpenSSLProbe).Dispatcher(0x1dc?, {0x5ddb60?, 0x4003e5a400?})
	/source_code/user/module/probe_openssl.go:700 +0x1c4
ecapture/user/module.(*Module).Dispatcher(0x4000126dc0, {0x5ddb60, 0x4003e5a400})
	/source_code/user/module/imodule.go:304 +0x120
ecapture/user/module.(*Module).perfEventReader.func1()
	/source_code/user/module/imodule.go:231 +0x21c
created by ecapture/user/module.(*Module).perfEventReader
	/source_code/user/module/imodule.go:199 +0x174

**To Reproduce**
1. Starting ecapture './ecapture tls -i wlan0 -w ecap.pcapng'
2. Click on 'MT App 12.13'

**Comment by cfc4n** [comment]
fixed at #398 , please try again.
